const fs = require('fs');

const keywordsData = [
    { kw: "car window tinting dubai", sv: 1300, sd: 30, pd: 81, cpc: "$16.29", topic: "Ultimate Guide to Car Window Tinting in Dubai: Costs, Rules & Top Brands", sec: ["best car window tinting dubai", "uae car window tinting rules", "carbon vs ceramic tint", "35 vs 20 window tint"] },
    { kw: "car battery replacement dubai", sv: 1000, sd: 19, pd: 66, cpc: "$43.15", topic: "Emergency Car Battery Replacement in Dubai: 24/7 Doorstep Service Guide", sec: ["car electrical repair dubai", "car scanning diagnostics dubai", "car computer diagnostic dubai"] },
    { kw: "car wrapping dubai", sv: 880, sd: 37, pd: 79, cpc: "$26.31", topic: "Car Wrapping in Dubai: Vinyl Wrap Costs, Colors, PPF & Legal Rules", sec: ["best car wrapping dubai", "car wrap vs car paint", "peelable paint vs wrap", "carbon fiber wrapping dubai"] },
    { kw: "car detailing in dubai", sv: 720, sd: 35, pd: 88, cpc: "$18.90", topic: "Professional Car Detailing in Dubai: Interior, Exterior & Engine Wash Packages", sec: ["benefits of car detailing", "car detailing dubai cost", "car interior cleaning dubai", "car engine wash dubai"] },
    { kw: "best car window tinting dubai", sv: 590, sd: 31, pd: 85, cpc: "$14.80", topic: "Top 10 Best Car Window Tinting Centers in Dubai (2026 Comparison)", sec: ["best car tint brands uae", "carbon vs ceramic tint", "uv protection for car windows"] },
    { kw: "how to find car paint code", sv: 590, sd: 26, pd: 12, cpc: "$0.00", topic: "How to Find Your Car Paint Code: Step-by-Step Guide for All Car Brands", sec: ["car painting service dubai", "luxury car paint color ideas", "car scratch repair dubai"] },
    { kw: "best car wrapping dubai", sv: 480, sd: 33, pd: 82, cpc: "$16.50", topic: "Best Car Wrapping Studios in Dubai: Matte, Gloss, Satin & Color Change", sec: ["car wrapping dubai", "car customization dubai", "luxury car customization trends"] },
    { kw: "car polish vs wax", sv: 480, sd: 30, pd: 25, cpc: "$0.80", topic: "Car Polish vs. Car Wax: What is the Difference and Which One Do You Need?", sec: ["car wax vs car polish", "car polishing dubai", "ceramic coating vs ppf dubai"] },
    { kw: "uae car window tinting rules", sv: 390, sd: 22, pd: 60, cpc: "$5.80", topic: "UAE Car Window Tinting Rules & Laws: Permitted Percentage, Fines & Regulations", sec: ["35 vs 20 window tint", "car window tinting dubai", "best car tint brands uae"] },
    { kw: "car ac repair dubai", sv: 320, sd: 23, pd: 57, cpc: "$35.33", topic: "Car AC Repair & Gas Refill in Dubai: Fast Cooling System Diagnostics", sec: ["car cooling system repair dubai", "car thermostat replacement dubai", "car water pump repair dubai"] },
    { kw: "car mechanic dubai", sv: 320, sd: 30, pd: 54, cpc: "$12.76", topic: "Best Car Mechanic & Auto Workshop in Dubai for German & Luxury Cars", sec: ["car engine repair dubai", "car computer diagnostic dubai", "pre purchase car inspection dubai"] },
    { kw: "car wax vs car polish", sv: 320, sd: 28, pd: 20, cpc: "$0.60", topic: "Car Wax vs. Polish: How to Protect Your Paint in Dubai's Harsh Desert Sun", sec: ["car polish vs wax", "car polishing dubai", "nano ceramic coating protection"] },
    { kw: "car wrap vs car paint", sv: 320, sd: 25, pd: 35, cpc: "$4.10", topic: "Car Wrap vs. Car Paint: Cost, Durability & Resale Value Comparison in UAE", sec: ["peelable paint vs wrap", "car painting service dubai", "car wrapping dubai"] },
    { kw: "best car tint brands uae", sv: 260, sd: 23, pd: 70, cpc: "$9.40", topic: "Best Car Tint Brands in UAE: 3M, Xpel, Huper Optik & Ceramic Review", sec: ["carbon vs ceramic tint", "uv protection for car windows", "car window tinting dubai"] },
    { kw: "carbon vs ceramic tint", sv: 260, sd: 21, pd: 35, cpc: "$2.10", topic: "Carbon vs. Ceramic Tint: Heat Rejection, Price & Clarity Compared", sec: ["35 vs 20 window tint", "best car tint brands uae", "uv protection for car windows"] },
    { kw: "benefits of car detailing", sv: 210, sd: 25, pd: 40, cpc: "$1.50", topic: "Top 7 Benefits of Regular Car Detailing for Preserving Your Luxury Vehicle", sec: ["car detailing in dubai", "car interior cleaning dubai", "car polishing dubai"] },
    { kw: "best paint protection film brands", sv: 210, sd: 24, pd: 60, cpc: "$6.20", topic: "Best Paint Protection Film (PPF) Brands in Dubai: STEK, Xpel & SunTek", sec: ["paint protection film dubai ppf", "ceramic coating vs ppf dubai", "car scratch repair dubai"] },
    { kw: "car interior cleaning dubai", sv: 210, sd: 31, pd: 86, cpc: "$11.62", topic: "Deep Car Interior Cleaning & Sanitization Service in Dubai", sec: ["car carpet cleaning dubai", "car leather upholstery repair", "seat upholstery dubai"] },
    { kw: "car polishing dubai", sv: 210, sd: 41, pd: 90, cpc: "$11.84", topic: "Professional Car Polishing & Paint Correction Services in Dubai", sec: ["car scratch repair dubai", "car polish vs wax", "car ceramic coating dubai"] },
    { kw: "car rim repair dubai", sv: 210, sd: 29, pd: 78, cpc: "$13.33", topic: "Car Rim Repair & Alloy Wheel Straightening Specialist in Dubai", sec: ["car rim painting dubai", "brake caliper painting dubai", "tyre balancing wheel alignment dubai"] },
    { kw: "car upholstery dubai", sv: 210, sd: 38, pd: 80, cpc: "$14.82", topic: "Custom Car Upholstery & Leather Seat Restoration Services in Dubai", sec: ["types of car upholstery", "car seat repair dubai", "seat upholstery dubai"] },
    { kw: "pre purchase car inspection dubai", sv: 210, sd: 33, pd: 90, cpc: "$14.54", topic: "Pre-Purchase Car Inspection Dubai: Comprehensive 150-Point Used Car Check", sec: ["car scanning diagnostics dubai", "car mechanic dubai", "flood car repair dubai"] },
    { kw: "uv protection for car windows", sv: 210, sd: 24, pd: 40, cpc: "$2.50", topic: "UV Protection for Car Windows: Block 99% Harmful Rays & Infrared Heat", sec: ["car window tinting dubai", "carbon vs ceramic tint", "uae car window tinting rules"] },
    { kw: "35 vs 20 window tint", sv: 170, sd: 14, pd: 10, cpc: "$0.00", topic: "35% vs. 20% Window Tint: Dark Heat Rejection vs. Legal Night Visibility", sec: ["uae car window tinting rules", "carbon vs ceramic tint", "best car tint brands uae"] },
    { kw: "car detailing dubai cost", sv: 140, sd: 28, pd: 75, cpc: "$12.40", topic: "How Much Does Car Detailing Cost in Dubai? Complete 2026 Price Guide", sec: ["car detailing in dubai", "benefits of car detailing", "car interior cleaning dubai"] },
    { kw: "ceramic coating maintenance", sv: 140, sd: 20, pd: 30, cpc: "$1.20", topic: "Ceramic Coating Maintenance Guide: How to Wash & Extend Protection Life", sec: ["ceramic coating aftercare", "nano ceramic coating protection", "car ceramic coating dubai"] },
    { kw: "ceramic coating explained", sv: 110, sd: 17, pd: 18, cpc: "$0.00", topic: "Ceramic Coating Explained: How Nano-Technology Protects Car Paint", sec: ["nano ceramic coating protection", "ceramic coating vs ppf dubai", "car polish vs wax"] },
    { kw: "g63 body kits mercedes g class", sv: 110, sd: 22, pd: 55, cpc: "$7.20", topic: "Mercedes-AMG G63 Body Kits & Brabus Upgrades in Dubai", sec: ["car body kits dubai", "car customization dubai", "how to get amg exhaust sound"] },
    { kw: "car ceramic coating dubai", sv: 90, sd: 9, pd: 75, cpc: "$19.04", topic: "Best Car Ceramic Coating Services in Dubai: 9H Hardness Protection", sec: ["ceramic coating maintenance", "ceramic coating aftercare", "nano ceramic coating protection"] },
    { kw: "ceramic coating aftercare", sv: 90, sd: 16, pd: 25, cpc: "$0.90", topic: "Essential Ceramic Coating Aftercare Rules: Do's and Don'ts After Application", sec: ["ceramic coating maintenance", "car ceramic coating dubai", "car polish vs wax"] },
    { kw: "flood car repair dubai", sv: 90, sd: 15, pd: 45, cpc: "$18.50", topic: "Flood Damaged Car Repair & Electrical Restoration Services in Dubai", sec: ["car computer diagnostic dubai", "car electrical repair dubai", "car engine repair dubai"] },
    { kw: "nano ceramic coating protection", sv: 90, sd: 18, pd: 50, cpc: "$3.40", topic: "Nano Ceramic Coating Protection: Hydrophobic Gloss & UV Defense", sec: ["car ceramic coating dubai", "ceramic coating explained", "ceramic coating maintenance"] },
    { kw: "types of car upholstery", sv: 90, sd: 18, pd: 22, cpc: "$0.00", topic: "Types of Car Upholstery Fabrics: Leather, Nappa, Alcantara & Vinyl Compared", sec: ["car upholstery dubai", "car seat upholstery cost uae", "seat upholstery dubai"] },
    { kw: "ceramic coating vs ppf dubai", sv: 70, sd: 16, pd: 82, cpc: "$14.20", topic: "Ceramic Coating vs. PPF in Dubai: Which Paint Protection is Best for You?", sec: ["best paint protection film brands", "car ceramic coating dubai", "car wrap vs car paint"] },
    { kw: "car upholstery cleaning and repair", sv: 70, sd: 20, pd: 48, cpc: "$5.00", topic: "Professional Car Upholstery Cleaning & Leather Restoration Guide", sec: ["car leather upholstery repair", "leather car seat scratch repair", "car seat repair dubai"] },
    { kw: "car seat upholstery cost uae", sv: 50, sd: 19, pd: 65, cpc: "$8.10", topic: "Car Seat Upholstery Cost in UAE: Leather Retrofitting & Repair Pricing", sec: ["types of car upholstery", "car upholstery dubai", "seat upholstery dubai"] },
    { kw: "luxury car paint color ideas", sv: 50, sd: 15, pd: 10, cpc: "$0.00", topic: "20 Trending Luxury Car Paint Colors & Custom Satin Finish Ideas", sec: ["car wrap vs car paint", "how to find car paint code", "luxury car customization trends"] },
    { kw: "car customization dubai", sv: 40, sd: 39, pd: 84, cpc: "$6.39", topic: "Luxury Car Customization Shop in Dubai: Body Kits, Interior & Performance Tuning", sec: ["car modification shop dubai", "g63 body kits mercedes g class", "starlight headliner star roof car"] },
    { kw: "car dent repair dubai", sv: 40, sd: 32, pd: 89, cpc: "$33.77", topic: "Paintless Dent Repair (PDR) & Bumper Scratch Repair in Dubai", sec: ["car scratch repair dubai", "car painting service dubai", "car body kits dubai"] },
    { kw: "clean mercedes leather seats", sv: 40, sd: 11, pd: 5, cpc: "$0.00", topic: "How to Safely Clean & Condition Mercedes Leather Seats Without Damage", sec: ["leather car seat scratch repair", "car leather steering wheel repair", "car leather upholstery repair"] },
    { kw: "brake pad replacement dubai", sv: 30, sd: 32, pd: 88, cpc: "$20.99", topic: "Brake Pad Replacement & Rotor Refacing Service in Dubai", sec: ["car brake repair dubai", "car brake disk replacement", "brake caliper painting dubai"] },
    { kw: "car engine repair dubai", sv: 30, sd: 10, pd: 14, cpc: "$0.00", topic: "Complete Car Engine Repair & Overhaul Specialist Workshop in Dubai", sec: ["car head gasket repair dubai", "car timing belt replacement", "car computer diagnostic dubai"] },
    { kw: "car interior repair dubai", sv: 30, sd: 35, pd: 99, cpc: "$16.71", topic: "Car Interior Repair & Dashboard Restoration Specialist in Dubai", sec: ["car dashboard repair dubai", "car door leather repair", "car roof upholstery dubai"] },
    { kw: "car scratch repair dubai", sv: 30, sd: 30, pd: 83, cpc: "$23.32", topic: "Express Car Scratch Removal & Paint Repair Studio in Dubai", sec: ["car dent repair dubai", "car polishing dubai", "car painting service dubai"] },
    { kw: "how to get amg exhaust sound", sv: 30, sd: 13, pd: 8, cpc: "$0.00", topic: "How to Get That Deep AMG Exhaust Sound on Your Vehicle", sec: ["car exhaust system installation", "car engine chip tuning", "car software change ecu tuning"] },
    { kw: "luxury car customization trends", sv: 30, sd: 14, pd: 15, cpc: "$0.00", topic: "Top Luxury Car Customization Trends in Dubai: Forged Carbon & Starlight Roofs", sec: ["starlight headliner star roof car", "g63 body kits mercedes g class", "carbon fiber wrapping dubai"] },
    { kw: "car electrical repair dubai", sv: 20, sd: 16, pd: 36, cpc: "$0.00", topic: "Auto Electrical Repair & ECU Diagnostic Specialists in Dubai", sec: ["car battery replacement dubai", "car computer diagnostic dubai", "car scanning diagnostics dubai"] },
    { kw: "car seat repair dubai", sv: 20, sd: 35, pd: 99, cpc: "$11.66", topic: "Car Seat Upholstery & Leather Tear Repair Services in Dubai", sec: ["leather car seat repair dubai", "car leather rip repair", "leather car seat scratch repair"] },
    { kw: "car suspension repair dubai", sv: 20, sd: 21, pd: 53, cpc: "$0.00", topic: "Car Suspension Repair & Shock Absorber Replacement in Dubai", sec: ["tyre balancing wheel alignment dubai", "car mechanic dubai", "pre purchase car inspection dubai"] },
    { kw: "peelable paint vs wrap", sv: 20, sd: 12, pd: 15, cpc: "$0.00", topic: "Peelable Paint Spray vs. Vinyl Wrap: Which Liquid Protection Is Better?", sec: ["car wrap vs car paint", "car wrapping dubai", "best car wrapping dubai"] },
    { kw: "brake caliper painting dubai", sv: 10, sd: 8, pd: 91, cpc: "$9.66", topic: "High-Heat Brake Caliper Painting & Custom Decal Service in Dubai", sec: ["car rim repair dubai", "car rim painting dubai", "brake pad replacement dubai"] },
    { kw: "car body kits dubai", sv: 10, sd: 15, pd: 33, cpc: "$0.00", topic: "Aerodynamic Car Body Kits & Custom Bumper Installation in Dubai", sec: ["g63 body kits mercedes g class", "carbon fiber wrapping dubai", "car customization dubai"] },
    { kw: "car brake repair dubai", sv: 10, sd: 9, pd: 11, cpc: "$0.00", topic: "Comprehensive Car Brake System Repair & Fluid Flush in Dubai", sec: ["brake pad replacement dubai", "car brake disk replacement", "brake caliper painting dubai"] },
    { kw: "car carpet cleaning dubai", sv: 10, sd: 36, pd: 100, cpc: "$0.00", topic: "Deep Steam Car Carpet Cleaning & Odor Removal Service in Dubai", sec: ["car interior cleaning dubai", "car detailing in dubai", "car upholstery dubai"] },
    { kw: "car computer diagnostic dubai", sv: 10, sd: 5, pd: 1, cpc: "$0.00", topic: "Full Computerized Car Scanning & Fault Code Reset in Dubai", sec: ["car scanning diagnostics dubai", "car electrical repair dubai", "car engine repair dubai"] },
    { kw: "car door leather repair", sv: 10, sd: 5, pd: 1, cpc: "$0.00", topic: "Car Door Panel & Leather Upholstery Scratch Repair Specialist", sec: ["car leather upholstery repair", "car interior repair dubai", "leather car seat scratch repair"] },
    { kw: "car engine oil change dubai", sv: 10, sd: 5, pd: 1, cpc: "$0.00", topic: "Fast Car Engine Oil & Filter Change Service Near Me in Dubai", sec: ["car mechanic dubai", "spark plug replacement dubai", "car engine wash dubai"] },
    { kw: "car headlight restoration dubai", sv: 10, sd: 18, pd: 43, cpc: "$0.00", topic: "Headlight Restoration & UV Protection Coating Service in Dubai", sec: ["car detailing in dubai", "car polishing dubai", "car scratch repair dubai"] },
    { kw: "car leather rip repair", sv: 10, sd: 5, pd: 1, cpc: "$0.00", topic: "Car Leather Rip & Seam Tear Repair Guide for Luxury Car Owners", sec: ["leather car seat repair dubai", "car seat repair dubai", "car leather upholstery repair"] },
    { kw: "car leather steering wheel repair", sv: 10, sd: 36, pd: 100, cpc: "$0.00", topic: "Car Leather Steering Wheel Repair & Re-stitching Services in Dubai", sec: ["clean mercedes leather seats", "car interior repair dubai", "car door leather repair"] },
    { kw: "car leather upholstery repair", sv: 10, sd: 33, pd: 93, cpc: "$0.00", topic: "Leather Car Seat Restoration & Dyeing Services in Dubai", sec: ["car seat repair dubai", "types of car upholstery", "car upholstery dubai"] },
    { kw: "car rust proofing dubai", sv: 10, sd: 24, pd: 62, cpc: "$0.00", topic: "Underbody Car Rust Proofing & Anti-Corrosion Protection in Dubai", sec: ["car scratch repair dubai", "pre purchase car inspection dubai", "car detailing in dubai"] },
    { kw: "car sound proofing dubai", sv: 10, sd: 31, pd: 85, cpc: "$10.47", topic: "Car Soundproofing & Thermal Insulation Dampening Installation in Dubai", sec: ["car interior repair dubai", "car customization dubai", "car roof upholstery dubai"] },
    { kw: "car timing belt replacement", sv: 10, sd: 7, pd: 6, cpc: "$0.00", topic: "Car Timing Belt & Water Pump Replacement Service Intervals", sec: ["car engine repair dubai", "car water pump repair dubai", "car mechanic dubai"] },
    { kw: "car transmission repair dubai", sv: 10, sd: 5, pd: 1, cpc: "$0.00", topic: "Automatic Gearbox & Car Transmission Repair Workshop in Dubai", sec: ["gearbox oil change dubai", "car gearbox repair dubai", "car mechanic dubai"] },
    { kw: "leather car seat scratch repair", sv: 10, sd: 5, pd: 1, cpc: "$0.00", topic: "How to Fix Leather Car Seat Scratches: DIY vs Professional Repair", sec: ["clean mercedes leather seats", "car leather rip repair", "car seat repair dubai"] },
    { kw: "seat upholstery dubai", sv: 10, sd: 44, pd: 100, cpc: "$0.00", topic: "Custom Seat Upholstery Design & Leather Recovers in Dubai", sec: ["car upholstery dubai", "types of car upholstery", "car seat upholstery cost uae"] }
];

let md = `### 🎯 Complete Content Strategy & Topic Plan (Focus & Secondary Keywords)\n\n`;
md += `| # | Proposed Article / Landing Page Topic (H1 Title) | Focus Keyword (Primary Target) | Secondary / LSI Keywords (Cluster Targets) | Search Volume | SEO Difficulty (SD) | CPC (USD) |\n`;
md += `|---|---|---|---|:---:|:---:|:---:|\n`;

keywordsData.forEach((item, idx) => {
    const secondaryStr = item.sec.map(s => `\`${s}\``).join(', ');
    md += `| ${idx + 1} | **${item.topic}** | **${item.kw}** | ${secondaryStr} | **${item.sv.toLocaleString()}** | ${item.sd} | ${item.cpc} |\n`;
});

fs.writeFileSync('c:\\Users\\ssght\\OneDrive\\Desktop\\nufka\\topics_content_plan.md', md, 'utf-8');
console.log(`Generated ${keywordsData.length} Content Topics.`);
